services:
  mcp-server:
    container_name: mcp
    build:
      context: ./mcp_server
      dockerfile: Dockerfile
    ports:
      - 8001:8001

  adk-web:
    container_name: adk
    build:
      context: ./multi_tool_agent
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mcp-server
      - ollama-server

  ollama-server:
    container_name: olama
    build:
      context: ./ollama
      dockerfile: Dockerfile
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama:
